version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecoride_web
    ports:
      - "8080:80"
    volumes:
      - ./src/public:/var/www/html
      - ./src:/var/www
    environment:
      - DB_HOST=db
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: ecoride_db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data:

